spring:
  application:
    name: PapillonMerchants
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/passbook?autoReconnect=true
    username: root
    password: 513520jl
  kafka:
    bootstrap-servers: 192.168.89.128:9092
    consumer:
      group-id: passbook
    listener:
      concurrency: 4

server:
  port: 9527

logging:
  level: debug
  file: papillon-merchats.log




