spring:
  application:
    name: Ivan-Passbook
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/passbook?autoReconnect=true&serverTimezone=GMT
    username: root
    password: 513520jl
    driver-class-name: com.mysql.cj.jdbc.Driver
  kafka:
    bootstrap-servers: 192.168.89.128:9092
    consumer:
      group-id: passbook
    listener:
      concurrency: 4

  data:
    hbase:
      quorum: 192.168.89.128:2181
      rootDir: hdfs://192.168.89.128:9000/hbase
      nodeParent: /hbase

  redis:
    host: 127.0.0.1
    port: 6379
server:
  port: 9528
logging:
  file: papillon-passbook.log
  level: debug




